# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/ruby:2.7

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "cloudflare-rails.gemspec" }}-{{ checksum "Appraisals" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install bundler
          command: |
            gem install bundler -v $(grep bundler cloudflare-rails.gemspec |awk {'print $4'}|sed "s/'//g")

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: install appraisal versions
          command: |
            bundle exec appraisal install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "cloudflare-rails.gemspec" }}-{{ checksum "Appraisals" }}

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec appraisal rake
      # collect reports
      - store_test_results:
          path: tmp/rspec
      - store_artifacts:
          path: tmp/rspec
          destination: test-results
